services:
  web:
    build: .
    container_name: lealink-web
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS:-:80}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
