"""Initial tables

Revision ID: 0001
Revises:
Create Date: 2026-09-27 19:13:34.104565
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('notify_requests', sa.Boolean(), nullable=False),
    sa.Column('notify_messages', sa.Boolean(), nullable=False),
    sa.Column('notify_expiring', sa.Boolean(), nullable=False),
    sa.Column('notify_matching', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('search_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_alerts_is_active'), 'search_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_search_alerts_user_id'), 'search_alerts', ['user_id'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('review_note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('accepting_students', sa.Boolean(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('about', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('levels', sa.JSON(), nullable=False),
    sa.Column('age_groups', sa.JSON(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('practical_experience', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('offline_location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('travel_radius_km', sa.Integer(), nullable=True),
    sa.Column('lesson_types', sa.JSON(), nullable=False),
    sa.Column('durations', sa.JSON(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('max_group_size', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('free_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_minutes', sa.Integer(), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('group_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_commitment', sa.Integer(), nullable=True),
    sa.Column('package_size', sa.Integer(), nullable=True),
    sa.Column('package_discount', sa.Integer(), nullable=True),
    sa.Column('contact_method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('contact_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('response_time_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teacher_profiles_status'), 'teacher_profiles', ['status'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_teacher_id'), 'certificates', ['teacher_id'], unique=False)
    op.create_table('lesson_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('for_whom', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('child_age', sa.Integer(), nullable=True),
    sa.Column('parent_contact', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('goal_details', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('lessons_per_week', sa.Integer(), nullable=False),
    sa.Column('lesson_duration', sa.Integer(), nullable=False),
    sa.Column('preferred_times', sa.JSON(), nullable=False),
    sa.Column('start_asap', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_duration', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('free_trial', sa.Boolean(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('decline_reason', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('decline_note', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_warning_sent', sa.Boolean(), nullable=False),
    sa.Column('learner_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('learner_last_read_id', sa.Integer(), nullable=False),
    sa.Column('teacher_last_read_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_requests_learner_id'), 'lesson_requests', ['learner_id'], unique=False)
    op.create_index(op.f('ix_lesson_requests_status'), 'lesson_requests', ['status'], unique=False)
    op.create_index(op.f('ix_lesson_requests_teacher_id'), 'lesson_requests', ['teacher_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['lesson_requests.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_request_id'), 'messages', ['request_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('admin_note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['lesson_requests.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('author_role', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['lesson_requests.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'author_id')
    )
    op.create_index(op.f('ix_reviews_request_id'), 'reviews', ['request_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_request_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_messages_request_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_lesson_requests_teacher_id'), table_name='lesson_requests')
    op.drop_index(op.f('ix_lesson_requests_status'), table_name='lesson_requests')
    op.drop_index(op.f('ix_lesson_requests_learner_id'), table_name='lesson_requests')
    op.drop_table('lesson_requests')
    op.drop_index(op.f('ix_certificates_teacher_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_teacher_profiles_status'), table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_search_alerts_user_id'), table_name='search_alerts')
    op.drop_index(op.f('ix_search_alerts_is_active'), table_name='search_alerts')
    op.drop_table('search_alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
